Docs: change main screenshot and links
ucl-contoso-chat/ucl-openai-search pull request #40
Opened 2024-08-30 22:41 UTC by nextedoff

## Purpose

Our fork looks slightly different than the original application, thus a screenshot that is used within main Readme file was replaced.
Also, the links for using Codespaces and Devcontainers were changed, to use this repository instead of the original repository.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Does this require changes to learn.microsoft.com docs?
- [ ] Yes
- [x] No

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes
- [ ] Other... Please describe:

## Code quality checklist
- [ ] The current tests all pass (`python -m pytest`).
- [ ] I added tests that prove my fix is effective or that my feature works
- [ ] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [ ] I ran `python -m mypy` to check for type errors
- [ ] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

2024-08-30 22:43 UTC, nextedoff commented
question: should I add a screenshot for 'evaluation' page and mention it inside the the main README.md?

2024-08-31 11:15 UTC, phoevos requested changes
Thanks!

Let's not merge this yet. We could add a video showcasing the basic functionality (if we end up recording it), as well as a screenshot of the evaluation page.

2024-08-31 11:15 UTC, phoevos commented on README.md
> -[📺 Watch a video overview of the app.](https://youtu.be/3acB0OWmLvM)
If we do record a video, it'd be nice to link it here as well.

2024-09-02 14:34 UTC, phoevos approved these changes

2024-09-02 14:35 UTC, merged